/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'outline-variant': '#bdc9c2',
        'primary-container': '#008060',
        'surface-container': '#eeeeef',
        'primary': '#00654b',
        'surface-container-highest': '#e2e2e3',
        'inverse-primary': '#75d9b3',
        'secondary-container': '#dfdfe0',
        'tertiary-container': '#6e7174',
        'on-error': '#ffffff',
        'primary-fixed-dim': '#75d9b3',
        'surface-variant': '#e2e2e3',
        'surface-container-lowest': '#ffffff',
        'surface-dim': '#dadadb',
        'on-secondary': '#ffffff',
        'on-tertiary-fixed-variant': '#44474a',
        'secondary-fixed': '#e2e2e3',
        'on-background': '#1a1c1d',
        'on-secondary-fixed-variant': '#454748',
        'tertiary-fixed-dim': '#c4c7ca',
        'on-secondary-fixed': '#1a1c1d',
        'on-tertiary-container': '#f4f6fa',
        'surface-bright': '#f9f9fa',
        'surface': '#f9f9fa',
        'on-primary-container': '#d6ffeb',
        'outline': '#6e7a73',
        'on-tertiary-fixed': '#191c1f',
        'surface-tint': '#006c50',
        'surface-container-low': '#f3f3f4',
        'error': '#ba1a1a',
        'inverse-surface': '#2f3132',
        'on-surface-variant': '#3e4944',
        'tertiary-fixed': '#e1e2e6',
        'secondary': '#5d5e60',
        'on-surface': '#1a1c1d',
        'error-container': '#ffdad6',
        'on-primary': '#ffffff',
        'on-secondary-container': '#616364',
        'on-tertiary': '#ffffff',
        'secondary-fixed-dim': '#c6c6c7',
        'tertiary': '#56595c',
        'inverse-on-surface': '#f0f1f2',
        'on-primary-fixed-variant': '#00513c',
        'background': '#f9f9fa',
        'surface-container-high': '#e8e8e9',
        'primary-fixed': '#92f6cf',
        'on-error-container': '#93000a',
        'on-primary-fixed': '#002116',
      },
      fontFamily: {
        display: ['Manrope', 'sans-serif'],
        'body-md': ['Manrope', 'sans-serif'],
        'h3': ['Manrope', 'sans-serif'],
        'body-lg': ['Manrope', 'sans-serif'],
        'label-md': ['Manrope', 'sans-serif'],
        'label-sm': ['Manrope', 'sans-serif'],
        'body-sm': ['Manrope', 'sans-serif'],
        'h1': ['Manrope', 'sans-serif'],
        'h2': ['Manrope', 'sans-serif'],
      },
      fontSize: {
        'display': ['48px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'h1': ['32px', { lineHeight: '1.25', letterSpacing: '-0.01em', fontWeight: '700' }],
        'h2': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'h3': ['20px', { lineHeight: '1.4', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '1', letterSpacing: '0.01em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '1', fontWeight: '500' }],
      },
      spacing: {
        'md': '24px',
        'margin': '32px',
        'base': '8px',
        'sm': '12px',
        'lg': '48px',
        'gutter': '24px',
        'xs': '4px',
        'xl': '80px',
        'container-max': '1280px',
      },
      borderRadius: {
        'DEFAULT': '0.5rem',
        'md': '0.75rem',
        'lg': '1rem',
        'xl': '1.5rem',
        'full': '9999px',
      },
      maxWidth: {
        'container-max': '1280px',
      },
    },
  },
  plugins: [],
}
